# Generated by Django 2.0.13 on 2019-09-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('eventOriginal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.Language'),
        ),
        migrations.AddField(
            model_name='event',
            name='published_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.PublishedState'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtranslation',
            unique_together={('eventOriginal', 'language')},
        ),
    ]
